# Generated by Django 4.2.4 on 2024-01-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('m_motto', models.CharField(max_length=200)),
                ('m_description', models.TextField()),
                ('m_genre', models.CharField(max_length=100)),
                ('m_director', models.CharField(max_length=25)),
                ('m_writer', models.CharField(max_length=25)),
                ('m_r_date', models.DateTimeField()),
                ('m_poster', models.ImageField(blank=True, null=True, upload_to='media/m_poster/')),
                ('m_backg_im', models.ImageField(blank=True, null=True, upload_to='media/m_bacground_image/')),
                ('m_trailer', models.URLField()),
                ('m_o_language', models.CharField(max_length=30)),
                ('m_status', models.CharField(max_length=20)),
                ('m_budget', models.IntegerField(max_length=50)),
                ('m_revenue', models.IntegerField(max_length=50)),
            ],
        ),
    ]
