# Generated by Django 4.2.4 on 2024-01-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='m_id',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='m_budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='m_revenue',
            field=models.IntegerField(),
        ),
    ]
