# Generated by Django 4.2.7 on 2024-01-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movieinfo_m_id_alter_movieinfo_m_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='m_adult',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='m_vote_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='m_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='m_genre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='m_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='m_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
