# Generated by Django 4.2.4 on 2024-01-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movieinfo_m_adult_movieinfo_m_vote_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='m_imdb_i',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='m_status',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='m_trailer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='m_vote_count',
            field=models.IntegerField(default=0.0),
        ),
    ]
